apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-pvc
  namespace: nemo
spec:
  storageClassName: ebs-auto-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi