apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-catalogue
  labels:
    app: eros
    type: frontend
    deployment: data-catalogue 
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: data-catalogue
  template:
    metadata:
      labels:
        app: eros
        type: frontend
        deployment: data-catalogue 
    spec:
      imagePullSecrets:
        - name: nemo-regcred
      containers:
        - name: data-catalogue
          image: marcothedood/eros4nrg-demo:data-catalogue-v1.6
          imagePullPolicy: Always
          ports:
            - containerPort: 8003
              protocol: TCP
          env:
            - name: POSTGRES_DB
              value: data
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-users
                  key: admin.password
