apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-catalogue
  labels:
    app: data-catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-catalogue
  template:
    metadata:
      labels:
        app: data-catalogue
    spec:
      imagePullSecrets:
        - name: marco-regcred
      containers:
        - name: data-catalogue
          image: marcothedood/eros4nrg-demo:data-catalogue-v1.7
          # resources:
          #   requests:
          #     memory: "1Gi"
          #     cpu: "500m"
          ports:
            - containerPort: 8003
              protocol: TCP
          env:
            - name: POSTGRES_DB
              value: data
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-users
                  key: admin.password
          imagePullPolicy: Always
