apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- postgres.yaml
- keycloak.yaml
- grafana.yaml
- data-catalogue.yaml
- data-pipeline.yaml
- minio.yaml
- iot-stream.yaml
- training-environment.yaml

configMapGenerator:
- name: grafana-emotion-dashboard
  files:
    - emotion.json=./grafana_provisioning/emotion_1755772424649.json
- name: grafana-asm-terni-dashboard
  files:
    - asm_terni.json=./grafana_provisioning/asm_terni_1740691866670.json
- name: grafana-dashboards
  files:
    - all.yaml=./grafana_provisioning/dashboards-config.yaml
- name: grafana-datasources
  files:
    - all.yaml=./grafana_provisioning/datasources.yaml