apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: eros
    type: backend
    deployment: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: postgres
  template:
    metadata:
      labels:
        app: eros
        type: backend
        deployment: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14-alpine
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-users
              key: admin.password
        - name: POSTGRES_USER
          value: admin
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: pg-volume
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: pg-volume
        persistentVolumeClaim:
          claimName: postgres-pvc