apiVersion: apps/v1
kind: Deployment
metadata:
  name: training-environment
  labels:
    app: training-environment
spec:
  replicas: 0
  selector:
    matchLabels:
      app: training-environment
  template:
    metadata:
      labels:
        app: training-environment
    spec:
      imagePullSecrets:
        - name: nemo-regcred
      containers:
        - name: training-environment
          image: nemometaos/eros-training-environment:v0.1.1
          ports:
            - containerPort: 8004
              protocol: TCP
          env:
            - name: POSTGRES_DB
              value: data
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-users
                  key: admin.password
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: admin
