apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nemo-svc

resources:
- ../../deploy/
- ../../secrets/
- ../../pvcs/
- ../../namespace/
- ../../svc/
- ../../ingress/
- ../../jobs/