apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-auto-sc
provisioner: ebs.csi.eks.amazonaws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp2
  fsType: ext4
  encrypted: "true"
allowVolumeExpansion: true