apiVersion: v1
kind: Service
metadata:
  name: data-pipeline
  labels:
    app: data-pipeline
spec:
  ports:
    - name: "8002"
      port: 8002 
      targetPort: 8002
  selector:
    app: data-pipeline