apiVersion: v1
kind: Service
metadata:
  name: data-catalogue
  labels:
    app: data-catalogue
spec:
  ports:
    - name: "8003"
      port: 8003 
      targetPort: 8003
  selector:
    app: data-catalogue