apiVersion: v1
kind: Service
metadata:
  name: data-catalogue
  labels:
    app: eros
    type: frontend
    service: data-catalogue
spec:
  selector:
    app: eros
    type: frontend
    deployment: data-catalogue
  ports:
    - name: http
      port: 80
      targetPort: 8003
  type: ClusterIP