apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: eros
    type: frontend
    service: grafana
spec:
  selector:
    app: eros
    type: frontend
    deployment: grafana
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: ClusterIP
