apiVersion: v1
kind: Service
metadata:
  name: training-environment
  labels:
    app: eros
    type: backend
    service: training-environment
spec:
  selector:
    app: eros
    type: backend
    deployment: training-environment
  ports:
    - name: training-environment
      port: 8004
      targetPort: 8004
  type: ClusterIP